repos:
  - repo: local
    hooks:
      - id: autoflake
        name : Remove unused variables and imports
        entry: autoflake
        language: python
        args: ["--in-place", "--remove-all-unused-imports", "--remove-unused-variables"]
        files: \.py$
      - id: black
        name: Format python code
        entry: black
        language: python
        types: [python]
        args: ["--line-length=79"]
      - id: isort
        name: Sort import statements
        entry: isort
        language: python
        args: ["--filter-files", "--profile", "black", "--line-length=79"]

