version: '3.4'

services:
  fxcm:
    image: fxcm
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DOCKER=1 
    ports:
      - 8000:8000
    volumes:
      - appdata:/var/www
    depends_on:
      - mongo
    networks:
      - backend
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    networks:
      - backend
    volumes:
      - mongodbdata:/data/db

networks:
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local