version: 2.1
orbs:
  poetry: talkiq/poetry@4.0.1

jobs:
  build:
    docker:
      - image: circleci/python:3.11
      - image: circleci/mongo:4.2
        environment:
          DEPLOY_ENV: ci
          MONGODB_USERNAME: username
          MONGODB_PASSWORD: password
    steps:
      - checkout
      - poetry/install
      - run:
          name: Install dependencies
          command: poetry install
      - run:
          name: Run tests
          command: poetry run pytest

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
