version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.0

jobs:
  build:
    docker:
      - image: cimg/python:3.11.5
      - image: circleci/mongo:4.2
        environment:
          DEPLOY_ENV: ci
          MONGODB_USERNAME: username
          MONGODB_PASSWORD: password
          POETRY_VERSION: latest
    steps:
      - checkout
      - run :
          name: Install Poetry
          command: |
            curl -sSL https://install.python-poetry.org | python -
            echo 'export PATH=$HOME/.poetry/bin:$PATH' >> $BASH_ENV
      - run:
          name: Install dependencies
          command: poetry install
      - run:
          name: Run tests
          command: poetry run pytest

  deploy:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - aws-cli/setup
      - run:
          name: Print environment variables
          command: |
            echo $ACCESS_KEY
            echo $ACCESS_SECRET
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set region us-east-1
      - run:
          name: Checkout fxcm repo
          command: |
            mkdir -p ~/.ssh
            touch ~/.ssh/known_hosts
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            git clone git@github.com:kev0h1/fxcm.git ~/fxcm
            cd ~/fxcm
            git checkout $CIRCLE_BRANCH
      - run:
          name: Checkout cdk repo
          command: |
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            git clone git@github.com:kev0h1/cdk_deploy.git ~/cdk_deploy
      - run:
          name: Change to cdk directory
          command: cd ~/cdk_deploy
      - run:
          name: Deploy with CDK
          command: cdk deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - hold-for-approval:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold-for-approval